# Add 'repo' label to any root file changes
repo:
  - ./*

client:
  - client/**/*

@client/components:
  - client/src/components/*

@client/pages:
  - client/src/pages/*

server:
  - server/**/*

@server/app:
  - server/app/*

docs:
  - docs/**/*

@docs/architechture:
  - docs/architechture/**/*

deployment:
  - deployment/**/*